apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: common-sandbox   # Change namespace here
spec:
  selector:
    app: nginx
    namespace: web-sandbox
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer