version: "3"

networks:
  local_net:
    driver: bridge

services:
  resources-api:
    networks: [local_net]
    build:
      context: ./
      dockerfile: ./ResourcesAPI/Dockerfile
    expose:
      - 5000:5000
    depends_on:
      - database
    environment:
      ASPNETCORE_URLS: http://*:5000
      MongoDB__ConnectionURI: mongodb://database:27017
      MongoDB__DatabaseName: microservices
      MongoDB__CollectionName: resource

  inventory-api:
    networks: [local_net]
    build:
      context: ./
      dockerfile: ./InventoryAPI/Dockerfile
    expose:
      - 5001:5001
    depends_on:
      - resources-api
      - database
    environment:
      ASPNETCORE_URLS: http://*:5001
      MongoDB__ConnectionURI: mongodb://database:27017
      MongoDB__DatabaseName: microservices
      MongoDB__CollectionName: inventory
      APIs__Resource: http://resources-api:5000/api/resource/

  clients-api:
    networks: [local_net]
    build:
      context: ./
      dockerfile: ./ClientsAPI/Dockerfile
    expose:
      - 5003:5003
    depends_on:
      - database
    environment:
      ASPNETCORE_URLS: http://*:5003
      MongoDB__ConnectionURI: mongodb://database:27017
      MongoDB__DatabaseName: microservices
      MongoDB__CollectionName: client

  renting-api:
    networks: [local_net]
    build:
      context: ./
      dockerfile: ./RentingAPI/Dockerfile
    expose:
      - 5004:5004
    depends_on:
      - database
      - resources-api
      - inventory-api
      - clients-api
    environment:
      ASPNETCORE_URLS: http://*:5004
      MongoDB__ConnectionURI: mongodb://database:27017
      MongoDB__DatabaseName: microservices
      MongoDB__CollectionName: renting
      APIs__Inventory: http://inventory-api:5001/api/inventory/
      APIs__Client: http://clients-api:5003/api/client/
      APIs__Resource: http://resources-api:5000/api/resource/

  database:
    networks: [local_net]
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./database:/data/db

  proxy:
    networks: [local_net]
    image: nginx:stable-alpine
    ports:
      - 80:80
    depends_on:
      - resources-api
      - inventory-api
      - clients-api
      - renting-api
      - front-end
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf

  front-end:
    networks: [local_net]
    build: ./Frontend
    volumes:
      - ./front-end-config.json:/usr/share/nginx/html/assets/json/config.json
