# docker compose -f .\docker-compose.yaml --project-name microsvcs up --detach
version: '3.8'
volumes:
  postgres-data:
  pgadmin-data:

networks:
  micro_net:
    driver: bridge

services:
  pgAdmin4:
    networks: [micro_net]
    container_name: ms-pgadmin4
    image: dpage/pgadmin4:8.5
    ports:
      - 8080:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - microservicesdb
    environment:
      PGADMIN_DEFAULT_EMAIL: jesus.acedo@unosquare.com
      PGADMIN_DEFAULT_PASSWORD: password
  microservicesdb:
    networks: [micro_net]
    container_name: ms-postgres
    image: postgres:16.2-alpine3.19
    restart: always
    environment:
      POSTGRES_PASSWORD: password.1
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
 